// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmtter, emitAsync, iferr,
    __slice = [].slice;

  EventEmtter = require('events').EventEmtter;

  iferr = function(fail, succ) {
    return function(err) {
      if (err != null) {
        return fail(err);
      } else {
        return succ();
      }
    };
  };

  emitAsync = function() {
    var a, cb, emitter, name, num, _i;
    emitter = arguments[0], name = arguments[1], a = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), cb = arguments[_i++];
    if (num = (emitter.listeners(name)).length) {
      return emitter.emit.apply(emitter, [name].concat(__slice.call(a), [iferr(cb, function() {
        if (!--num) {
          return cb();
        }
      })]));
    } else {
      return cb();
    }
  };

  emitAsync.install = function(emitter) {
    if (emitter == null) {
      emitter = EventEmitter.prototype;
    }
    return emitter.emitAsync = function() {
      var a;
      a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return emitAsync.apply(null, [this].concat(__slice.call(a)));
    };
  };

  module.exports = emitAsync;

}).call(this);
